runtime: go111
#api_version: go1

env_variables:
  APP_TOPIC: 'playground-s-11-488719-items'


handlers:
- url: /public
  static_dir: public

- url: /images
  static_dir: public/images

- url: /assets
  static_dir: public/assets

- url: /.*
  script: auto
  #script: _go_app
  #login: required